begin;
create extension if not exists pgtap with schema extensions;
select plan(14);
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='app_private.withdrawal_external_send_keys'::regclass),'key registry enables and forces RLS');
select ok(not has_table_privilege('anon','app_private.withdrawal_external_send_keys','SELECT,INSERT,UPDATE,DELETE'),'anon cannot read or mutate transfer keys');
select ok(not has_table_privilege('authenticated','app_private.withdrawal_external_send_keys','SELECT,INSERT,UPDATE,DELETE'),'members cannot read or mutate transfer keys');
select ok(has_table_privilege('service_role','app_private.withdrawal_external_send_keys','SELECT'),'server role can read exact replay binding');
select ok(has_table_privilege('service_role','app_private.withdrawal_external_send_keys','INSERT'),'server role can append successful aliases');
select ok(not has_table_privilege('service_role','app_private.withdrawal_external_send_keys','UPDATE,DELETE'),'server role cannot edit or remove previous key bindings');
select ok(exists(select 1 from pg_constraint where conrelid='app_private.withdrawal_external_send_keys'::regclass and contype='p'),'key uniqueness is database enforced');
select ok(exists(select 1 from pg_constraint where conrelid='app_private.withdrawal_external_send_keys'::regclass and contype='f' and confrelid='public.withdrawal_external_sends'::regclass),'aliases reference canonical sends');
select ok(exists(select 1 from pg_trigger where tgrelid='app_private.withdrawal_external_send_keys'::regclass and not tgisinternal and tgenabled='O' and tgfoid='app_private.prevent_row_mutation()'::regprocedure),'append-only trigger remains enabled');
select ok(exists(select 1 from pg_constraint where conrelid='app_private.withdrawal_external_send_keys'::regclass and conname='withdrawal_external_send_key_length' and contype='c'),'registry retains bounded request key contract');
select ok(exists(select 1 from pg_policy where polrelid='app_private.withdrawal_external_send_keys'::regclass and polroles=array[(select oid from pg_roles where rolname='service_role')]),'registry policy is server role only');
select ok(not has_function_privilege('anon','public.record_krw_external_send(uuid,text,bigint,uuid,timestamp with time zone,text)','EXECUTE') and not has_function_privilege('authenticated','public.record_krw_external_send(uuid,text,bigint,uuid,timestamp with time zone,text)','EXECUTE'),'KRW RPC remains unavailable to public and members');
select ok(not has_function_privilege('anon','public.record_usdt_external_send(uuid,text,text,numeric,jsonb,uuid,timestamp with time zone,text)','EXECUTE') and not has_function_privilege('authenticated','public.record_usdt_external_send(uuid,text,text,numeric,jsonb,uuid,timestamp with time zone,text)','EXECUTE'),'USDT RPC remains unavailable to public and members');
select ok(has_function_privilege('service_role','public.record_krw_external_send(uuid,text,bigint,uuid,timestamp with time zone,text)','EXECUTE') and has_function_privilege('service_role','public.record_usdt_external_send(uuid,text,text,numeric,jsonb,uuid,timestamp with time zone,text)','EXECUTE'),'authorized server RPC contract is preserved');
select * from finish();
rollback;
